### ISSUE TITLE
File endpoint hardcoded (getFile)

### ISSUE THREAD

**Issue by foremtehan** [telegram-bot-sdk/laravel#11]
When using [telegram-bot-api](https://github.com/tdlib/telegram-bot-api) as telegram server, it has different path for the `file` endp;oint which comes from getFile, But the file endpoint hardcoded [here](https://github.com/telegram-bot-sdk/telegram-bot-sdk/blob/fa7cfa330460bb9ea56bb8687639f5da8bdbda62/src/Http/TelegramClient.php#L138)

I was trying to send a PR for this but i couldn't figure it out where is the usage of telegram.php in the codebase?

I mean this item:

https://github.com/telegram-bot-sdk/laravel/blob/547ee486b9e70c76dbf81fa858095273cea81150/config/telegram.php#L107C1-L112

**Comment by irazasyed** [comment]
Share a sample URL? Currently the SDK does not support configuration for the file endpoint but I can look into it and consider adding the support for customization if there's sample data.

**Comment by foremtehan** [comment]
To get the path a file we should use getFile right? it return:

this is coming from from https://api.telegram.org/botTOKEN/getFile?file_id=FILE_ID

![image](https://github.com/telegram-bot-sdk/laravel/assets/53290883/b646a025-3a09-4a13-bcdc-9c5684013bbe)

So to download this file we should put the file_path to this endpoint:

https://api.telegram.org/file/bot<token>/<file_path>
look at the `file` keyword in this url

But the problem is when using telegram-bot-api as a standalone telegram server, it return something like:

```
     all: [
       "ok" => true,
       "result" => [
         "file_id" => "qweqwe-Dc1EMLkisBAAdtAAMrBA",
         "file_unique_id" => "AQqweADoQ4AqwegJYGVNqwe",
         "file_size" => 1216,
         "file_path" => "/var/lib/telegram-bot-api/BOT_TOKEN/thumbnails/file_159.jpg",
       ],
     ],
   }
```

To download this file we have to put `file_path` to this endpoint:

```
http://localhost:8081/var/lib/telegram-bot-api/BOT_TOKEN/thumbnails/file_159.jpg
```

As you can see there is no `file` keyword in the above url

**Comment by irazasyed** [comment]
I've just added the support to set a custom file url template. You can manually set by calling `withFileUrl(string $fileUrl)` method or set it in config under `http` -> `file_url`.

Commit:
https://github.com/telegram-bot-sdk/telegram-bot-sdk/commit/3a449a9d3d8aa5d8d1598146a811fa31000ac8e6

Default Template: `{BASE_API_URL}/file/bot{TOKEN}/{FILE_PATH}`

# Usage

## Config
```php
// ...
'http' => [
	// ..
	'file_url' => '{BASE_API_URL}/file/bot{TOKEN}/{FILE_PATH}',
	// ...
],
// ...
```

## On-the-fly

```php
Telegram::withFileUrl('{BASE_API_URL}/file/bot{TOKEN}/{FILE_PATH}');
```

### Supported Shortcodes

> These shortcodes get replaced with appropriate values in the template.

- `{BASE_API_URL}`: Your Base API URL or default `https://api.telegram.org`.
- `{TOKEN}`: Bot token depending on which bot you make the call from.
- `{FILE_PATH}`: The path you provide to the `getFileUrl($path)` method.
