### ISSUE TITLE
[Bug]: Route [telegram.bot.webhook] not defined.

### ISSUE THREAD

**Issue by bigperson** [telegram-bot-sdk/laravel#14]
### PHP version

8.3

### Telegram Bot SDK version

dev-main

### Laravel version (if any)

11.7

### What happened?

php artisan telegram:webhook:setup
Setting webhook for [default] bot!
Route [telegram.bot.webhook] not defined.

### Code To Reproduce the bug

php artisan telegram:webhook:setup

**Comment by vserdobintsev** [comment]
В классе Telegram\Bot\Laravel\Console\Webhook\WebhookInfoCommand в методе presentLastErrorDate необходимо добавить ещё одну проверку:
```
    protected function presentLastErrorDate(ResponseObject $webhook): ?Carbon
    {
        return $webhook->last_error_date && $webhook->last_error_date !== 0
            ? Carbon::createFromTimestamp($webhook->last_error_date, config('app.timezone'))
            : null;
    }
```
После этого всё будет работать. Надеюсь, разработчики внесут правки.

**Comment by jonnywilliamson** [comment]
I have seen this before. The problem is the telegram/larave service provider is deferrred 

If you cache the routes it should work

`artisan route:cache`
